### ISSUE TITLE
feature Request: Doorbell quick replies

### ISSUE THREAD

**Issue by Rvh91** [JimStar/reolink_cctv#148] opened 2023-01-03 12:52 UTC
Hi, 

Thanks for the great work on the integration. 
I was wondering if it is possible to have a service or button to trigger the three quick replies from the doorbell.
Thanks!

**Comment by JimStar** [comment] 2023-01-03 21:11
Duplicate of #124.

**Closed by JimStar** 2023-01-03 21:11 UTC
