### ISSUE TITLE
error translating * response for channel

### ISSUE THREAD

**Issue by etamtlosz** [JimStar/reolink_cctv#28] opened 2022-10-17 22:37 UTC
**Describe the bug**
The following error shows up in my log. I don't know if is related to #18 , so I open a separate issue.

**To Reproduce**
It just appeared overnight, no one was using HA at that time.

**Expected behavior**
n/a

**Debug log would be very helpful**
logger is set to debug, but unfortunately has grown to more than two million lines in just ~12 hours. Pastebin won't allow such huge files, but here are some lines around the time of the error.
https://pastebin.com/YCZrGPcg

**Environment:**

Home Assistant 2022.10.4
Supervisor 2022.10.0
Operating System 9.2

NVR:
RLN8-410
build 2208150
N3MB01
v3.0.0.200_22081500

Cameras 4x:
RLC-810A
build 22041503
IPC_523128M8MP
v3.1.0.956_22041503

**Comment by JimStar** [comment] 2022-10-17 22:42
Duplicate of #18

**Comment by JimStar** [comment] 2022-10-17 22:42
Thank you for the log! I will continue in #18 about that...

**Closed by JimStar** 2022-10-17 22:42 UTC
