### ISSUE TITLE
Integration has no entities

### ISSUE THREAD

**Issue by PedroQ** [JimStar/reolink_cctv#75] opened 2022-11-23 12:14 UTC
**Describe the bug**
After the latest updates (0.33, 0.34), the integration doesn't add any entities for my camera.
I tried to remove the device and reconfigure it, the setup process works, but no entities are added.
I also tried removing the integration and installing an earlier version (0.32) but for some reason the issue persists.

**Steps To Reproduce**
Have a camera configured
Update to version 0.0.34
Verify that the integration no longer exposes entities

Remove the configured camera
Configure the Reolink integration to add the camera
After completing the setup flow, the integration is created but adds no device or entities.

**Expected behavior**
The integration should expose the entities for the camera.

**Debug log would be very helpful**
[home-assistant.log](https://github.com/JimStar/reolink_cctv/files/10075301/home-assistant.log)

**Screenshots**
![image](https://user-images.githubusercontent.com/1912048/203543876-5832be74-d217-4a76-a833-9dc75327869b.png)

**Environment:**
Please provide useful information about your environment, like:
 - Home Assistant 2022.11.4
 - Reolink E1 Zoom fw v3.0.0.1107_22070508

**Comment by DarwinData** [comment] 2022-11-23 13:11
Same here.  This was working prior to .34 update with RLC-410W camera.

**Comment by JimStar** [comment] 2022-11-23 18:35
BTW, did you try to update your camera firmware to the latest one?  
I just see that your camera does not support a command that is stated in the recent official Reolink's API v7 manual. Either they just ignored to make the firmware up to date with it just for **some** cameras, or you just have not updated to the latest version...

**Comment by PedroQ** [comment] 2022-11-23 18:45
> BTW, did you try to update your camera firmware to the latest one? I just see that your camera does not support a command that is stated in the recent official Reolink's API v7 manual. Either they just ignored to make the firmware up to date with it just for **some** cameras, or you just have not updated to the latest version...

I did, thinking that it could be related to something like that. The latest firmware for my camera was from July. It didn't seem to solve the issue, so that's probably a command specific to some models/firmware builds.

**Comment by JimStar** [comment] 2022-11-24 04:59
Must be fixed in [0.0.35](https://github.com/JimStar/reolink_cctv/releases/tag/0.0.35).

**Comment by cob94440** [comment] 2022-11-24 08:42
![image](https://user-images.githubusercontent.com/62489067/203734193-b7aac0ad-14fe-485f-9225-27b38db3babc.png)
Same problem on latest version 0.0.35

**Comment by JimStar** [comment] 2022-11-24 08:44
I need a full debug log, taken with 0.0.35...

**Comment by Barma-lej** [comment] 2022-11-24 12:05
Model: E1 Zoom
Build No.: build 22070508
Hardware No.: IPC_515BSD6
Config Version: v3.0.0.0
Firmware Version: v3.0.0.1107_22070508
Details: IPC_515BSD6xxxxxxxxxxxxxxx

It is no more entity and no log for the camera

**Comment by PedroQ** [comment] 2022-11-24 12:07
> Must be fixed in [0.0.35](https://github.com/JimStar/reolink_cctv/releases/tag/0.0.35).
I can confirm that the issue is fixed for me. Thanks!

**Comment by Barma-lej** [comment] 2022-11-24 12:14
[0.0.35](https://github.com/JimStar/reolink_cctv/releases/tag/0.0.35) is pre-release, so in HACS i had only 0.0.34.
[0.0.35](https://github.com/JimStar/reolink_cctv/releases/tag/0.0.35) fixed the issue. Thanks

**Comment by DarwinData** [comment] 2022-11-24 16:40
Thanks for the fix but I am not seeing .35 on HACS just yet.

**Comment by cob94440** [comment] 2022-11-24 16:41
Still non entities for me

**Comment by JimStar** [comment] 2022-11-24 17:04
I've just removed pre-release status from **0.0.35**, so it must be seen in HACS now.

Looks like it fixed the issue. Those who still has it maybe just need to restart HA... At least I don't see any debug logs I asked for.  
Just remember I don't have all the possible cameras to test on. It works for my NVR without any problems. If it doesn't for you, the only way for me to see what's happening is a full log with **debug enabled** (lines to enable are in every issue template).

**Comment by cob94440** [comment] 2022-11-24 19:44
Here is my log 
[reolink.txt](https://github.com/JimStar/reolink_cctv/files/10087007/reolink.txt)

**Comment by JimStar** [comment] 2022-11-24 19:52
@cob94440  
Thank you for the log, I see the problem with your model now. Easy to fix, will release a new quick-fix version after I'm back home.

**Comment by cob94440** [comment] 2022-11-24 20:00
Great Thanks a lot

**Comment by DarwinData** [comment] 2022-11-24 23:01
Just wanted to let you know that .35 is working on my stand alone RLC-410W camera.  Thanks for the help.

**Comment by JimStar** [comment] 2022-11-25 05:22
This regression for older devices (like RLN8-410-E) must now be fixed in [0.0.36](https://github.com/JimStar/reolink_cctv/releases/tag/0.0.36).

**Closed by JimStar** 2022-11-25 05:22 UTC

**Comment by cob94440** [comment] 2022-11-25 08:04
Great it works thanks
