### ISSUE TITLE
A lot of "error translating..." error messages in the log

### ISSUE THREAD

**Issue by cesarrew** [JimStar/reolink_cctv#129] opened 2022-12-21 16:03 UTC
**Describe the bug**
A lot of "error translating..." error messages in the log. I couldn't identify if this errors are causing problems using de integration, but it seems a problem to me.

**To Reproduce**
Just install the integration and setup de cameras.

**Expected behavior**
No erros in the log.

**Debug log would be very helpful**
Full log file attached.

**Screenshots**
Screenshot attached.

**Environment:**
Please provide useful information about your environment, like:
 - Home Assistant: 2022.12.7
 - Reolink NVR/camera model: 3 - E1 Zoom and 1 -  RLC-822A
 - NVR/camera firmware: RLC-822A - v3.1.0.989_22081907 / E1 Zoom (all 3) - v3.0.0.1107_22070508
 - reolink_cvtt: reolink_cctv-0.1.9.zip

**Additional context**
Kind of errors:

1- error translating channel-state response for channel 0: Expecting value: line 1 column 1 (char 0)
2- error translating of "Search" command response to json: Expecting value: line 1 column 1 (char 0)
3- error translating All Motion States response for channel 0: Expecting value: line 1 column 1 (char 0)
![log_error](https://user-images.githubusercontent.com/17600341/208948627-345f2519-3e7e-407d-b34a-1ec4685f87a3.png)
[full_log_reolink_error.zip](https://github.com/JimStar/reolink_cctv/files/10279274/full_log_reolink_error.zip)

**Comment by JimStar** [comment] 2022-12-21 18:19
Duplicate of #18, #28.

**Closed by JimStar** 2022-12-21 18:19 UTC
